version: '3.7'
services:
  server:
    build: '.'
    env_file:
      - .env
    ports:
      - 3000:3000
    # depends_on:
    #   - postgres
    networks:
      - test_vm
    command: yarn test -i

  # postgres:
  #   image: postgres:13-alpine
  #   container_name: postgres
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - .env
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   networks:
  #     - test_vm

networks:
  test_vm:
# volumes:
#   postgres:
#     name: postgres
