name: Continuous Integration (PR)

on:
  pull_request:
    branches: release

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      PORT: ${{ secrets.PORT }}
      BASE_PASSWORD: ${{ secrets.BASE_PASSWORD }}
      SECRET: ${{ secrets.SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Cancel workflow
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn migrate
      - run: yarn seed
      - run: yarn test -i
