name: Deploy

on:
  push:
    branches:
      - master
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      PORT: ${{ secrets.PORT }}
      BASE_PASSWORD: ${{ secrets.BASE_PASSWORD }}
      SECRET: ${{ secrets.SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Cancel workflow
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'restapi'
          heroku_email: ${{secrets.EMAIL}}
